[project]
name = "investing-for-programmers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alpha-vantage>=3.0.0",
    "dotenv>=0.9.9",
    "jupyterlab>=4.5.1",
    "matplotlib>=3.10.8",
    "yfinance>=0.2.66",
]
